version: '3.9'
services:
  fiber-frontend:
    build: 
      context: ./frontend
      dockerfile: ./React/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    stdin_open: true

  fiber-backend:
    build: 
      context: ./backend
      dockerfile: ./Golang/Dockerfile
    ports:
      - 4000:3000
    volumes:
      - ./backend:/backend

  fiber-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb

  fiber-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: fiber-mongo
    depends_on:
      - fiber-mongo